import type { Permission } from '@/lib/auth/permissions';
import * as kpi from '@/lib/validation/bi-kpi';
import * as objectives from '@/lib/validation/bi-objectives';
import * as finance from '@/lib/validation/bi-finance';
import * as governance from '@/lib/validation/bi-governance';
import * as knowledge from '@/lib/validation/bi-knowledge';
import * as reports from '@/lib/validation/bi-reports';
import * as ai from '@/lib/validation/bi-ai';
import * as q from '@/lib/validation/queries';
import type { Guard, RouteDoc } from './openapi-routes';

/**
 * Endpunkte der Unternehmensführung (`/api/bi/…`).
 *
 * Eigene Datei, weil es über neunzig Operationen sind und die Hauptliste
 * sonst unlesbar würde. Die Schemas sind dieselben Zod-Objekte wie zur
 * Laufzeit; der Abgleich in `generate-openapi.ts` prüft Pfad, Methode und
 * Schutz gegen den Dateibaum.
 */

const perm = (mode: 'all' | 'any', ...permissions: Permission[]): Guard => ({ kind: 'permissions', permissions, mode });

const T = {
  kpi: 'Führung: Kennzahlen',
  ziele: 'Führung: Ziele',
  finanzen: 'Führung: Finanzplanung',
  risiko: 'Führung: Risiko und Qualität',
  wissen: 'Führung: Wissen und Markt',
  berichte: 'Führung: Berichte',
} as const;

export const BI_ROUTES: RouteDoc[] = [
  // --- Kennzahlen und Cockpit --------------------------------------------------
  { method: 'get', path: '/api/bi/kpis', tag: T.kpi, summary: 'Kennzahlen mit jüngstem Wert', description: 'Alle Definitionen mit aktuellem und vorangehendem Monatswert, Vorjahresvergleich und Zielwert.', guard: perm('all', 'kpi:read'), rateLimit: 'apiRead', query: kpi.kpiListQuery },
  { method: 'post', path: '/api/bi/kpis', tag: T.kpi, summary: 'Kennzahl anlegen', description: 'Berechnete Kennzahlen brauchen einen Rechner im Code (422 sonst); manuelle werden von Hand nachgeführt.', guard: perm('all', 'kpi:manage'), rateLimit: 'apiWrite', body: kpi.createKpiDefinitionSchema, status: 201, extraErrors: [422] },
  { method: 'get', path: '/api/bi/kpis/{id}', tag: T.kpi, summary: 'Kennzahl mit Zielwerten', description: 'Definition samt periodenbezogenen Zielwerten.', guard: perm('all', 'kpi:read'), rateLimit: 'apiRead', params: q.idParam },
  { method: 'patch', path: '/api/bi/kpis/{id}', tag: T.kpi, summary: 'Kennzahl ändern', description: 'Zielwert, Warnschwelle, Gewicht und Anzeige. Der Schlüssel bleibt — er hängt an Snapshots. Warnschwelle und Ziel müssen zur Richtung passen (422).', guard: perm('all', 'kpi:manage'), rateLimit: 'apiWrite', params: q.idParam, body: kpi.updateKpiDefinitionSchema, extraErrors: [422] },
  { method: 'delete', path: '/api/bi/kpis/{id}', tag: T.kpi, summary: 'Kennzahl löschen', description: 'Nicht möglich, solange Schlüsselergebnisse daran messen (422).', guard: perm('all', 'kpi:manage'), rateLimit: 'apiWrite', params: q.idParam, status: 204, extraErrors: [422] },
  { method: 'get', path: '/api/bi/kpis/{id}/series', tag: T.kpi, summary: 'Verlauf einer Kennzahl', description: 'Festgeschriebene Snapshots einer Periodenart, älteste zuerst, mit Ziel- und Vorjahreswert.', guard: perm('all', 'kpi:read'), rateLimit: 'apiRead', params: q.idParam, query: kpi.kpiSeriesQuery },
  { method: 'post', path: '/api/bi/kpis/{id}/value', tag: T.kpi, summary: 'Manuellen Wert eintragen', description: 'Nur für Kennzahlen mit Herkunft MANUAL — ein Handwert an einer berechneten würde vom Nachtlauf überschrieben (422).', guard: perm('all', 'kpi:manage'), rateLimit: 'apiWrite', params: q.idParam, body: kpi.manualKpiValueSchema, status: 201, extraErrors: [422] },
  { method: 'post', path: '/api/bi/kpis/{id}/targets', tag: T.kpi, summary: 'Zielwert für eine Periode', description: 'Die Ausnahme vom Dauerwert, etwa ein höheres Ziel im Saisonquartal.', guard: perm('all', 'kpi:manage'), rateLimit: 'apiWrite', params: q.idParam, body: kpi.kpiTargetSchema, status: 201 },
  { method: 'patch', path: '/api/bi/kpis/weights', tag: T.kpi, summary: 'Gewichte im Gesundheitswert', description: 'Mehrere Gewichte in einem Aufruf; mindestens eines muss über null liegen (422).', guard: perm('all', 'kpi:manage'), rateLimit: 'apiWrite', body: kpi.healthWeightsSchema, extraErrors: [422] },
  { method: 'get', path: '/api/bi/cockpit', tag: T.kpi, summary: 'Führungscockpit', description: 'Gesundheitswert mit Herleitung, Kennzahlgruppen, Auffälligkeiten, Ziele, Risikomatrix, Fälliges. Finanzgruppen nur mit `cockpit:financials`.', guard: perm('all', 'cockpit:view'), rateLimit: 'apiRead', query: kpi.cockpitQuery },
  { method: 'get', path: '/api/bi/cockpit/health', tag: T.kpi, summary: 'Gesundheitswert', description: 'Aktueller Wert mit Komponenten, Teilnoten und Verlauf der letzten zwölf Monate.', guard: perm('all', 'cockpit:view'), rateLimit: 'apiRead' },
  { method: 'post', path: '/api/bi/cockpit/health', tag: T.kpi, summary: 'Gesundheitswert festschreiben', description: 'Schreibt den heutigen Wert samt Herleitung — sonst macht das der Nachtlauf.', guard: perm('all', 'kpi:manage'), rateLimit: 'apiWrite' },
  { method: 'get', path: '/api/bi/cockpit/insights', tag: T.kpi, summary: 'Auffälligkeiten', description: 'Regelbasierte Hinweise mit Verweis auf die Stelle, wo man etwas tun kann.', guard: perm('all', 'cockpit:view'), rateLimit: 'apiRead' },

  // --- Ziele ---------------------------------------------------------------------
  { method: 'get', path: '/api/bi/objectives', tag: T.ziele, summary: 'Ziele auflisten', description: 'Strategien, Ziele und Initiativen. Mitarbeitende sehen die eigenen und die freigegebenen Firmenziele — die Grenze zieht der Dienst.', guard: perm('any', 'objective:read', 'objective:read_own'), rateLimit: 'apiRead', query: objectives.objectiveListQuery },
  { method: 'post', path: '/api/bi/objectives', tag: T.ziele, summary: 'Ziel anlegen', description: 'Mit Flughöhe, Ebene, Zeitraum und Prüfzyklus. Die verantwortliche Person wird benachrichtigt.', guard: perm('all', 'objective:create'), rateLimit: 'apiWrite', body: objectives.createObjectiveSchema, status: 201 },
  { method: 'get', path: '/api/bi/objectives/timeline', tag: T.ziele, summary: 'Roadmap', description: 'Ziele mit Zeitraum für die Zeitachse.', guard: perm('any', 'objective:read', 'objective:read_own'), rateLimit: 'apiRead', query: objectives.objectiveTimelineQuery },
  { method: 'get', path: '/api/bi/objectives/{id}', tag: T.ziele, summary: 'Ziel mit Schlüsselergebnissen', description: 'Samt Check-ins, Massnahmen, Unterzielen und Sitzungen.', guard: perm('any', 'objective:read', 'objective:read_own'), rateLimit: 'apiRead', params: q.idParam },
  { method: 'patch', path: '/api/bi/objectives/{id}', tag: T.ziele, summary: 'Ziel ändern', description: 'Ein Ziel kann nicht sein eigenes übergeordnetes Ziel sein (422).', guard: perm('all', 'objective:update'), rateLimit: 'apiWrite', params: q.idParam, body: objectives.updateObjectiveSchema, extraErrors: [422] },
  { method: 'delete', path: '/api/bi/objectives/{id}', tag: T.ziele, summary: 'Ziel löschen', description: 'Papierkorb — Check-ins und Aufgaben bleiben.', guard: perm('all', 'objective:delete'), rateLimit: 'apiWrite', params: q.idParam, status: 204 },
  { method: 'post', path: '/api/bi/objectives/{id}/key-results', tag: T.ziele, summary: 'Schlüsselergebnis anlegen', description: 'Mit Kennzahl automatisch aus dem Nachtlauf; ohne manuell.', guard: perm('all', 'objective:update'), rateLimit: 'apiWrite', params: q.idParam, body: objectives.createKeyResultSchema, status: 201 },
  { method: 'post', path: '/api/bi/objectives/{id}/tasks', tag: T.ziele, summary: 'Massnahme als Aufgabe', description: 'Eine gewöhnliche Aufgabe mit Bezug zum Ziel.', guard: perm('all', 'objective:update'), rateLimit: 'apiWrite', params: q.idParam, body: objectives.objectiveTaskSchema, status: 201 },
  { method: 'post', path: '/api/bi/objectives/{id}/duplicate', tag: T.ziele, summary: 'Ziel duplizieren', description: 'Kopie als Entwurf mit Schlüsselergebnissen, ohne Verlauf.', guard: perm('all', 'objective:create'), rateLimit: 'apiWrite', params: q.idParam, status: 201 },
  { method: 'post', path: '/api/bi/objectives/{id}/review', tag: T.ziele, summary: 'Prüfung abschliessen', description: 'Setzt den nächsten Prüftermin um den Zyklus nach hinten.', guard: perm('all', 'objective:update'), rateLimit: 'apiWrite', params: q.idParam, body: objectives.reviewNoteSchema },
  { method: 'patch', path: '/api/bi/key-results/{id}', tag: T.ziele, summary: 'Schlüsselergebnis ändern', description: 'Start-, Ziel- und aktueller Wert; der Fortschritt wird neu gerechnet.', guard: perm('all', 'objective:update'), rateLimit: 'apiWrite', params: q.idParam, body: objectives.updateKeyResultSchema },
  { method: 'delete', path: '/api/bi/key-results/{id}', tag: T.ziele, summary: 'Schlüsselergebnis löschen', description: 'Mit Check-ins.', guard: perm('all', 'objective:update'), rateLimit: 'apiWrite', params: q.idParam, status: 204 },
  { method: 'post', path: '/api/bi/key-results/{id}/checkin', tag: T.ziele, summary: 'Check-in', description: 'Neuer Wert mit Kommentar. Automatische Schlüsselergebnisse weisen ab (422); Mitarbeitende nur an eigenen Zielen (404).', guard: perm('all', 'objective:checkin'), rateLimit: 'apiWrite', params: q.idParam, body: objectives.keyResultCheckinSchema, status: 201, extraErrors: [422] },

  // --- Finanzplanung -------------------------------------------------------------
  { method: 'get', path: '/api/bi/budgets', tag: T.finanzen, summary: 'Budgetperioden', description: 'Mit Plansumme und Zeilenzahl.', guard: perm('all', 'budget:read'), rateLimit: 'apiRead', query: finance.budgetListQuery },
  { method: 'post', path: '/api/bi/budgets', tag: T.finanzen, summary: 'Budgetperiode anlegen', description: 'In der Regel ein Geschäftsjahr.', guard: perm('all', 'budget:create'), rateLimit: 'apiWrite', body: finance.createBudgetPeriodSchema, status: 201 },
  { method: 'get', path: '/api/bi/budgets/{id}', tag: T.finanzen, summary: 'Budget mit Zeilen', description: 'Periode samt Zeilen und Monatsverteilung.', guard: perm('all', 'budget:read'), rateLimit: 'apiRead', params: q.idParam },
  { method: 'patch', path: '/api/bi/budgets/{id}', tag: T.finanzen, summary: 'Budget ändern', description: 'Nicht mehr nach Abschluss (422).', guard: perm('all', 'budget:update'), rateLimit: 'apiWrite', params: q.idParam, body: finance.updateBudgetPeriodSchema, extraErrors: [422] },
  { method: 'delete', path: '/api/bi/budgets/{id}', tag: T.finanzen, summary: 'Budget löschen', description: 'Nur Entwürfe (422).', guard: perm('all', 'budget:delete'), rateLimit: 'apiWrite', params: q.idParam, status: 204, extraErrors: [422] },
  { method: 'get', path: '/api/bi/budgets/{id}/variance', tag: T.finanzen, summary: 'Budgetabweichung', description: 'Plan, anteiliger Plan, Ist aus den Ausgaben, Abweichung und Hochrechnung je Zeile.', guard: perm('all', 'budget:read'), rateLimit: 'apiRead', params: q.idParam, query: finance.depreciationQuery },
  { method: 'post', path: '/api/bi/budgets/{id}/approve', tag: T.finanzen, summary: 'Budget genehmigen', description: 'Friert die Planwerte ein; Korrekturen laufen danach als Nachtrag (422 ohne Zeilen oder bereits genehmigt).', guard: perm('all', 'budget:approve'), rateLimit: 'apiWrite', params: q.idParam, extraErrors: [422] },
  { method: 'post', path: '/api/bi/budgets/{id}/close', tag: T.finanzen, summary: 'Budget abschliessen', description: 'Danach ist nichts mehr änderbar.', guard: perm('all', 'budget:approve'), rateLimit: 'apiWrite', params: q.idParam, extraErrors: [422] },
  { method: 'post', path: '/api/bi/budgets/{id}/lines', tag: T.finanzen, summary: 'Budgetzeile anlegen', description: 'Nur im Entwurf (422). Ohne Monatsverteilung wird gleichmässig verteilt.', guard: perm('all', 'budget:update'), rateLimit: 'apiWrite', params: q.idParam, body: finance.createBudgetLineSchema, status: 201, extraErrors: [422] },
  { method: 'patch', path: '/api/bi/budget-lines/{id}', tag: T.finanzen, summary: 'Budgetzeile ändern', description: 'Nach Genehmigung nur Nachtrag, Bezeichnung und Notiz (422 sonst).', guard: perm('all', 'budget:update'), rateLimit: 'apiWrite', params: q.idParam, body: finance.updateBudgetLineSchema, extraErrors: [422] },
  { method: 'delete', path: '/api/bi/budget-lines/{id}', tag: T.finanzen, summary: 'Budgetzeile löschen', description: 'Nur im Entwurf (422).', guard: perm('all', 'budget:update'), rateLimit: 'apiWrite', params: q.idParam, status: 204, extraErrors: [422] },
  { method: 'get', path: '/api/bi/investments', tag: T.finanzen, summary: 'Investitionen', description: 'Mit Restwert zum heutigen Tag.', guard: perm('all', 'investment:read'), rateLimit: 'apiRead', query: finance.investmentListQuery },
  { method: 'post', path: '/api/bi/investments', tag: T.finanzen, summary: 'Investition erfassen', description: 'Lineare oder degressive Abschreibung braucht die Nutzungsdauer; degressiv zudem einen Restwert über null (422).', guard: perm('all', 'investment:create'), rateLimit: 'apiWrite', body: finance.createInvestmentSchema, status: 201, extraErrors: [422] },
  { method: 'get', path: '/api/bi/investments/register', tag: T.finanzen, summary: 'Anlagenverzeichnis', description: 'Anlagen in Betrieb mit Anschaffungswert, kumulierter Abschreibung und Restwert zum Stichtag.', guard: perm('all', 'investment:read'), rateLimit: 'apiRead', query: finance.depreciationQuery },
  { method: 'get', path: '/api/bi/investments/{id}', tag: T.finanzen, summary: 'Investition', description: 'Mit Bewertung, ROI und Dateien.', guard: perm('all', 'investment:read'), rateLimit: 'apiRead', params: q.idParam },
  { method: 'patch', path: '/api/bi/investments/{id}', tag: T.finanzen, summary: 'Investition ändern', description: 'Statuswechsel auf „in Betrieb" setzt ohne Angabe das heutige Datum als Inbetriebnahme.', guard: perm('all', 'investment:update'), rateLimit: 'apiWrite', params: q.idParam, body: finance.updateInvestmentSchema, extraErrors: [422] },
  { method: 'delete', path: '/api/bi/investments/{id}', tag: T.finanzen, summary: 'Investition löschen', description: 'Papierkorb.', guard: perm('all', 'investment:delete'), rateLimit: 'apiWrite', params: q.idParam, status: 204 },
  { method: 'get', path: '/api/bi/investments/{id}/depreciation', tag: T.finanzen, summary: 'Abschreibungsplan', description: 'Restwert zum Stichtag und Plan je Nutzungsjahr — gerechnet, nicht gespeichert.', guard: perm('all', 'investment:read'), rateLimit: 'apiRead', params: q.idParam, query: finance.depreciationQuery },
  { method: 'get', path: '/api/bi/scenarios', tag: T.finanzen, summary: 'Szenarien', description: 'Nach Jahr und Art.', guard: perm('all', 'scenario:read'), rateLimit: 'apiRead', query: finance.scenarioListQuery },
  { method: 'post', path: '/api/bi/scenarios', tag: T.finanzen, summary: 'Szenario anlegen', description: 'Ohne Annahmen aus den letzten zwölf Monaten vorbelegt; wird sofort gerechnet.', guard: perm('all', 'scenario:manage'), rateLimit: 'apiWrite', body: finance.createScenarioSchema, status: 201 },
  { method: 'get', path: '/api/bi/scenarios/suggest', tag: T.finanzen, summary: 'Treiber aus dem Ist', description: 'Vorschlag für die Annahmen aus Buchungen, Einsätzen, Ausgaben und Zahlungen der letzten zwölf Monate.', guard: perm('all', 'scenario:read'), rateLimit: 'apiRead' },
  { method: 'get', path: '/api/bi/scenarios/compare', tag: T.finanzen, summary: 'Szenarien vergleichen', description: 'Alle Szenarien eines Jahres oder ausdrücklich genannte nebeneinander.', guard: perm('all', 'scenario:read'), rateLimit: 'apiRead', query: finance.scenarioCompareQuery },
  { method: 'get', path: '/api/bi/scenarios/{id}', tag: T.finanzen, summary: 'Szenario', description: 'Mit Annahmen und gespeichertem Ergebnis.', guard: perm('all', 'scenario:read'), rateLimit: 'apiRead', params: q.idParam },
  { method: 'patch', path: '/api/bi/scenarios/{id}', tag: T.finanzen, summary: 'Szenario ändern', description: 'Annahmen werden als Ganzes ersetzt; danach wird neu gerechnet und das Ergebnis zurückgegeben.', guard: perm('all', 'scenario:manage'), rateLimit: 'apiWrite', params: q.idParam, body: finance.updateScenarioSchema, extraErrors: [422] },
  { method: 'delete', path: '/api/bi/scenarios/{id}', tag: T.finanzen, summary: 'Szenario löschen', description: 'Papierkorb.', guard: perm('all', 'scenario:manage'), rateLimit: 'apiWrite', params: q.idParam, status: 204 },
  { method: 'post', path: '/api/bi/scenarios/{id}/compute', tag: T.finanzen, summary: 'Szenario rechnen', description: 'Neu rechnen und Ergebnis speichern (422 ohne Annahmen).', guard: perm('all', 'scenario:manage'), rateLimit: 'apiWrite', params: q.idParam, extraErrors: [422] },

  // --- Risiko und Qualität ---------------------------------------------------------
  { method: 'get', path: '/api/bi/risks', tag: T.risiko, summary: 'Risikoregister', description: 'Nach Schwere, mit Stufe (gering bis kritisch).', guard: perm('all', 'risk:read'), rateLimit: 'apiRead', query: governance.riskListQuery },
  { method: 'post', path: '/api/bi/risks', tag: T.risiko, summary: 'Risiko erfassen', description: 'Die Schwere setzt der Dienst aus Wahrscheinlichkeit × Auswirkung.', guard: perm('all', 'risk:create'), rateLimit: 'apiWrite', body: governance.createRiskSchema, status: 201 },
  { method: 'get', path: '/api/bi/risks/matrix', tag: T.risiko, summary: 'Risikomatrix', description: '5×5-Matrix offener Risiken mit Stufenzählung und den fünf schwersten.', guard: perm('all', 'risk:read'), rateLimit: 'apiRead' },
  { method: 'get', path: '/api/bi/risks/{id}', tag: T.risiko, summary: 'Risiko', description: 'Mit Massnahmen, Dateien und Prüfverlauf.', guard: perm('all', 'risk:read'), rateLimit: 'apiRead', params: q.idParam },
  { method: 'patch', path: '/api/bi/risks/{id}', tag: T.risiko, summary: 'Risiko ändern', description: 'Bewertung, Status, Verantwortung, Zyklus.', guard: perm('all', 'risk:update'), rateLimit: 'apiWrite', params: q.idParam, body: governance.updateRiskSchema },
  { method: 'delete', path: '/api/bi/risks/{id}', tag: T.risiko, summary: 'Risiko löschen', description: 'Papierkorb.', guard: perm('all', 'risk:delete'), rateLimit: 'apiWrite', params: q.idParam, status: 204 },
  { method: 'post', path: '/api/bi/risks/{id}/review', tag: T.risiko, summary: 'Risiko prüfen', description: 'Prüfung abschliessen, wahlweise neu bewerten; die Notiz landet im Verlauf.', guard: perm('all', 'risk:update'), rateLimit: 'apiWrite', params: q.idParam, body: governance.riskReviewSchema },
  { method: 'get', path: '/api/bi/controls', tag: T.risiko, summary: 'Kontrollen', description: 'Abläufe, Qualitätsnormen, Compliance-Pflichten und Notfallpläne.', guard: perm('all', 'control:read'), rateLimit: 'apiRead', query: governance.controlListQuery },
  { method: 'post', path: '/api/bi/controls', tag: T.risiko, summary: 'Kontrolle anlegen', description: 'Mit Prüfzyklus und Nachweisbeschreibung.', guard: perm('all', 'control:create'), rateLimit: 'apiWrite', body: governance.createControlSchema, status: 201 },
  { method: 'get', path: '/api/bi/controls/{id}', tag: T.risiko, summary: 'Kontrolle', description: 'Mit Massnahmen, Dateien und Prüfverlauf.', guard: perm('all', 'control:read'), rateLimit: 'apiRead', params: q.idParam },
  { method: 'patch', path: '/api/bi/controls/{id}', tag: T.risiko, summary: 'Kontrolle ändern', description: 'Angaben, Status, Zyklus.', guard: perm('all', 'control:update'), rateLimit: 'apiWrite', params: q.idParam, body: governance.updateControlSchema },
  { method: 'delete', path: '/api/bi/controls/{id}', tag: T.risiko, summary: 'Kontrolle löschen', description: 'Papierkorb.', guard: perm('all', 'control:delete'), rateLimit: 'apiWrite', params: q.idParam, status: 204 },
  { method: 'post', path: '/api/bi/controls/{id}/review', tag: T.risiko, summary: 'Kontrolle prüfen', description: 'Ergebnis „in Ordnung" oder „Abweichung"; Abweichung setzt den Status.', guard: perm('all', 'control:update'), rateLimit: 'apiWrite', params: q.idParam, body: governance.controlReviewSchema },
  { method: 'get', path: '/api/bi/actions', tag: T.risiko, summary: 'Massnahmen', description: 'Korrektur-, Vorbeugungs- und Verbesserungsmassnahmen, offen zuerst.', guard: perm('all', 'action:read'), rateLimit: 'apiRead', query: governance.actionListQuery },
  { method: 'post', path: '/api/bi/actions', tag: T.risiko, summary: 'Massnahme eröffnen', description: 'Zu einem Risiko, einer Kontrolle oder einer Bewertung. Mit Zuständigkeit entsteht eine Aufgabe.', guard: perm('all', 'action:create'), rateLimit: 'apiWrite', body: governance.createActionSchema, status: 201 },
  { method: 'patch', path: '/api/bi/actions/{id}', tag: T.risiko, summary: 'Massnahme ändern', description: 'Abschliessen und Wirksamkeit bestätigen — letzteres erst nach Abschluss (422).', guard: perm('all', 'action:update'), rateLimit: 'apiWrite', params: q.idParam, body: governance.updateActionSchema, extraErrors: [422] },

  // --- Wissen, Dokumente, Markt, Sitzungen ------------------------------------------
  { method: 'get', path: '/api/bi/documents', tag: T.wissen, summary: 'Dokumente', description: 'Im Rahmen der Sichtbarkeit: Mitarbeitende sehen STAFF-Dokumente und die eigene Personalakte.', guard: perm('any', 'document:read', 'document:read_own'), rateLimit: 'apiRead', query: knowledge.documentListQuery },
  { method: 'post', path: '/api/bi/documents', tag: T.wissen, summary: 'Dokument ablegen', description: 'Akte mit optionaler erster Fassung. Personaldokumente werden ohne Angabe EMPLOYEE_PRIVATE und brauchen die betroffene Person (422).', guard: perm('all', 'document:create'), rateLimit: 'apiWrite', body: knowledge.createDocumentSchema, status: 201, extraErrors: [422] },
  { method: 'get', path: '/api/bi/documents/{id}', tag: T.wissen, summary: 'Dokument', description: 'Akte mit allen Fassungen.', guard: perm('any', 'document:read', 'document:read_own'), rateLimit: 'apiRead', params: q.idParam },
  { method: 'patch', path: '/api/bi/documents/{id}', tag: T.wissen, summary: 'Dokument ändern', description: 'Angaben, Fristen, Sichtbarkeit.', guard: perm('all', 'document:update'), rateLimit: 'apiWrite', params: q.idParam, body: knowledge.updateDocumentSchema, extraErrors: [422] },
  { method: 'delete', path: '/api/bi/documents/{id}', tag: T.wissen, summary: 'Dokument löschen', description: 'Papierkorb; Fassungen bleiben im Speicher.', guard: perm('all', 'document:delete'), rateLimit: 'apiWrite', params: q.idParam, status: 204 },
  { method: 'post', path: '/api/bi/documents/{id}/versions', tag: T.wissen, summary: 'Neue Fassung', description: 'Die neue Datei wird die geltende Fassung.', guard: perm('all', 'document:create'), rateLimit: 'apiWrite', params: q.idParam, body: knowledge.addDocumentVersionSchema, status: 201 },
  { method: 'get', path: '/api/bi/documents/{id}/download', tag: T.wissen, summary: 'Dokument herunterladen', description: 'Protokollierte Weiterleitung auf einen befristeten Verweis; ohne `version` die geltende Fassung.', guard: perm('any', 'document:read', 'document:read_own'), rateLimit: 'apiRead', params: q.idParam, query: knowledge.documentDownloadQuery, produces: 'application/octet-stream' },
  { method: 'get', path: '/api/bi/knowledge', tag: T.wissen, summary: 'Wissensartikel', description: 'Nach Sichtbarkeit; Entwürfe nur für Schreibende.', guard: perm('all', 'knowledge:read'), rateLimit: 'apiRead', query: knowledge.articleListQuery },
  { method: 'post', path: '/api/bi/knowledge', tag: T.wissen, summary: 'Artikel verfassen', description: 'Der Slug entsteht aus dem Titel.', guard: perm('all', 'knowledge:create'), rateLimit: 'apiWrite', body: knowledge.createArticleSchema, status: 201 },
  { method: 'get', path: '/api/bi/knowledge/{id}', tag: T.wissen, summary: 'Artikel', description: 'Ein Artikel im Rahmen der Sichtbarkeit.', guard: perm('all', 'knowledge:read'), rateLimit: 'apiRead', params: q.idParam },
  { method: 'patch', path: '/api/bi/knowledge/{id}', tag: T.wissen, summary: 'Artikel ändern', description: 'Inhalt, Status, Sichtbarkeit; ein neuer Titel ergibt einen neuen Slug.', guard: perm('all', 'knowledge:update'), rateLimit: 'apiWrite', params: q.idParam, body: knowledge.updateArticleSchema },
  { method: 'delete', path: '/api/bi/knowledge/{id}', tag: T.wissen, summary: 'Artikel löschen', description: 'Papierkorb.', guard: perm('all', 'knowledge:delete'), rateLimit: 'apiWrite', params: q.idParam, status: 204 },
  { method: 'get', path: '/api/bi/competitors', tag: T.wissen, summary: 'Wettbewerber', description: 'Alle erfassten Wettbewerber.', guard: perm('all', 'market:read'), rateLimit: 'apiRead' },
  { method: 'post', path: '/api/bi/competitors', tag: T.wissen, summary: 'Wettbewerber erfassen', description: 'Mit Preisspanne, Stärken, Schwächen und Prüfzyklus.', guard: perm('all', 'market:manage'), rateLimit: 'apiWrite', body: knowledge.createCompetitorSchema, status: 201 },
  { method: 'patch', path: '/api/bi/competitors/{id}', tag: T.wissen, summary: 'Wettbewerber ändern', description: 'Jede Änderung gilt als Überprüfung.', guard: perm('all', 'market:manage'), rateLimit: 'apiWrite', params: q.idParam, body: knowledge.updateCompetitorSchema },
  { method: 'delete', path: '/api/bi/competitors/{id}', tag: T.wissen, summary: 'Wettbewerber löschen', description: 'Papierkorb.', guard: perm('all', 'market:manage'), rateLimit: 'apiWrite', params: q.idParam, status: 204 },
  { method: 'get', path: '/api/bi/market-insights', tag: T.wissen, summary: 'Marktbeobachtungen', description: 'Mit Kennzeichnung veralteter Einträge.', guard: perm('all', 'market:read'), rateLimit: 'apiRead', query: knowledge.marketListQuery },
  { method: 'post', path: '/api/bi/market-insights', tag: T.wissen, summary: 'Beobachtung erfassen', description: 'Mit Quelle, Datum und Geltungsdauer.', guard: perm('all', 'market:manage'), rateLimit: 'apiWrite', body: knowledge.createMarketInsightSchema, status: 201 },
  { method: 'patch', path: '/api/bi/market-insights/{id}', tag: T.wissen, summary: 'Beobachtung ändern', description: 'Aktualisieren gilt als Bestätigung ab heute.', guard: perm('all', 'market:manage'), rateLimit: 'apiWrite', params: q.idParam, body: knowledge.updateMarketInsightSchema },
  { method: 'delete', path: '/api/bi/market-insights/{id}', tag: T.wissen, summary: 'Beobachtung löschen', description: 'Papierkorb.', guard: perm('all', 'market:manage'), rateLimit: 'apiWrite', params: q.idParam, status: 204 },
  { method: 'get', path: '/api/bi/analysis', tag: T.wissen, summary: 'Analysetafeln', description: 'SWOT- und PESTEL-Tafeln, alle Fassungen.', guard: perm('all', 'market:read'), rateLimit: 'apiRead', query: knowledge.analysisListQuery },
  { method: 'post', path: '/api/bi/analysis', tag: T.wissen, summary: 'Tafel anlegen', description: 'Wahlweise als Nachfolgerin einer bestehenden Tafel derselben Art (422 bei falscher Art oder bereits abgelöst).', guard: perm('all', 'market:manage'), rateLimit: 'apiWrite', body: knowledge.createAnalysisBoardSchema, status: 201, extraErrors: [422] },
  { method: 'get', path: '/api/bi/analysis/{id}', tag: T.wissen, summary: 'Tafel', description: 'Mit Einträgen und Fassungskette.', guard: perm('all', 'market:read'), rateLimit: 'apiRead', params: q.idParam },
  { method: 'patch', path: '/api/bi/analysis/{id}', tag: T.wissen, summary: 'Tafel ändern', description: 'Nur die aktuelle Fassung; Einträge werden als Ganzes ersetzt (422 bei abgelöster Fassung).', guard: perm('all', 'market:manage'), rateLimit: 'apiWrite', params: q.idParam, body: knowledge.updateAnalysisBoardSchema, extraErrors: [422] },
  { method: 'delete', path: '/api/bi/analysis/{id}', tag: T.wissen, summary: 'Tafel löschen', description: 'Endgültig.', guard: perm('all', 'market:manage'), rateLimit: 'apiWrite', params: q.idParam, status: 204 },
  { method: 'get', path: '/api/bi/meetings', tag: T.wissen, summary: 'Sitzungen', description: 'Neueste zuerst, mit Teilnehmenden und Pendenzenzahl.', guard: perm('all', 'meeting:read'), rateLimit: 'apiRead', query: knowledge.meetingListQuery },
  { method: 'post', path: '/api/bi/meetings', tag: T.wissen, summary: 'Sitzung anlegen', description: 'Pendenzen werden als Aufgaben angelegt; Zuständige werden benachrichtigt.', guard: perm('all', 'meeting:create'), rateLimit: 'apiWrite', body: knowledge.createMeetingSchema, status: 201 },
  { method: 'get', path: '/api/bi/meetings/{id}', tag: T.wissen, summary: 'Sitzung', description: 'Mit Teilnehmenden, Aufgaben und Dateien.', guard: perm('all', 'meeting:read'), rateLimit: 'apiRead', params: q.idParam },
  { method: 'patch', path: '/api/bi/meetings/{id}', tag: T.wissen, summary: 'Sitzung ändern', description: 'Protokoll, Beschlüsse, Teilnehmende; weitere Pendenzen als Aufgaben.', guard: perm('all', 'meeting:update'), rateLimit: 'apiWrite', params: q.idParam, body: knowledge.updateMeetingSchema },
  { method: 'delete', path: '/api/bi/meetings/{id}', tag: T.wissen, summary: 'Sitzung löschen', description: 'Papierkorb; erzeugte Aufgaben bleiben.', guard: perm('all', 'meeting:delete'), rateLimit: 'apiWrite', params: q.idParam, status: 204 },

  // --- Berichte und Assistent --------------------------------------------------------
  { method: 'get', path: '/api/bi/report-schedules', tag: T.berichte, summary: 'Berichtszeitpläne', description: 'Mit letztem Lauf und nächstem Termin.', guard: perm('all', 'bireport:read'), rateLimit: 'apiRead' },
  { method: 'post', path: '/api/bi/report-schedules', tag: T.berichte, summary: 'Zeitplan anlegen', description: 'Wiederkehrender Bericht; der Nachtlauf erzeugt und verschickt ihn.', guard: perm('all', 'bireport:manage'), rateLimit: 'apiWrite', body: reports.createReportScheduleSchema, status: 201 },
  { method: 'patch', path: '/api/bi/report-schedules/{id}', tag: T.berichte, summary: 'Zeitplan ändern', description: 'Takt, Format, Empfänger, aktiv/pausiert.', guard: perm('all', 'bireport:manage'), rateLimit: 'apiWrite', params: q.idParam, body: reports.updateReportScheduleSchema },
  { method: 'delete', path: '/api/bi/report-schedules/{id}', tag: T.berichte, summary: 'Zeitplan löschen', description: 'Erzeugte Berichte bleiben.', guard: perm('all', 'bireport:manage'), rateLimit: 'apiWrite', params: q.idParam, status: 204 },
  { method: 'get', path: '/api/bi/reports', tag: T.berichte, summary: 'Erzeugte Berichte', description: 'Neueste zuerst, mit Status und Datei.', guard: perm('all', 'bireport:read'), rateLimit: 'apiRead', query: reports.reportListQuery },
  { method: 'post', path: '/api/bi/reports/generate', tag: T.berichte, summary: 'Bericht erzeugen', description: 'PDF, Excel oder Word für einen Zeitraum; die Datei bleibt liegen.', guard: perm('all', 'bireport:manage'), rateLimit: 'apiWrite', body: reports.generateReportSchema, status: 201 },
  { method: 'get', path: '/api/bi/reports/{id}/download', tag: T.berichte, summary: 'Bericht herunterladen', description: 'Protokollierte Weiterleitung auf einen befristeten Verweis (422, wenn der Bericht nicht bereit ist).', guard: perm('all', 'bireport:read'), rateLimit: 'apiRead', params: q.idParam, produces: 'application/octet-stream', extraErrors: [422] },
  { method: 'post', path: '/api/bi/assistant', tag: T.berichte, summary: 'Führungsassistent', description: 'Eine Fähigkeit je Aufruf (`kind`). Jede Antwort trägt Begründung, Datenquellen und Vertrauensgrad und ist ein Entwurf. Ohne ANTHROPIC_API_KEY 503.', guard: perm('all', 'cockpit:view', 'ai:use'), rateLimit: 'aiGenerate', body: ai.biAssistantSchema, extraErrors: [503] },
];
